#! /bin/sh

sxhkd &

bspc monitor eDP1 -d 'code' 'web' 'vchat' 'doc' 'music' 'games' 'adm'
#bspc monitor HDMI-1 -d F

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a weechat desktop='^3'
bspc rule -a mpv desktop='^3' focus=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
